// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: lession.proto

package lesson

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating        float32                `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lesson) Reset() {
	*x = Lesson{}
	mi := &file_lession_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lesson) ProtoMessage() {}

func (x *Lesson) ProtoReflect() protoreflect.Message {
	mi := &file_lession_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lesson.ProtoReflect.Descriptor instead.
func (*Lesson) Descriptor() ([]byte, []int) {
	return file_lession_proto_rawDescGZIP(), []int{0}
}

func (x *Lesson) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lesson) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lesson) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type LessonId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LessonId) Reset() {
	*x = LessonId{}
	mi := &file_lession_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LessonId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LessonId) ProtoMessage() {}

func (x *LessonId) ProtoReflect() protoreflect.Message {
	mi := &file_lession_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LessonId.ProtoReflect.Descriptor instead.
func (*LessonId) Descriptor() ([]byte, []int) {
	return file_lession_proto_rawDescGZIP(), []int{1}
}

func (x *LessonId) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_lession_proto protoreflect.FileDescriptor

const file_lession_proto_rawDesc = "" +
	"\n" +
	"\rlession.proto\"D\n" +
	"\x06Lesson\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x02R\x06rating\"\x1a\n" +
	"\bLessonId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id20\n" +
	"\rLessonService\x12\x1f\n" +
	"\tgetLesson\x12\t.LessonId\x1a\a.LessonB\n" +
	"Z\b./lessonb\x06proto3"

var (
	file_lession_proto_rawDescOnce sync.Once
	file_lession_proto_rawDescData []byte
)

func file_lession_proto_rawDescGZIP() []byte {
	file_lession_proto_rawDescOnce.Do(func() {
		file_lession_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lession_proto_rawDesc), len(file_lession_proto_rawDesc)))
	})
	return file_lession_proto_rawDescData
}

var file_lession_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lession_proto_goTypes = []any{
	(*Lesson)(nil),   // 0: Lesson
	(*LessonId)(nil), // 1: LessonId
}
var file_lession_proto_depIdxs = []int32{
	1, // 0: LessonService.getLesson:input_type -> LessonId
	0, // 1: LessonService.getLesson:output_type -> Lesson
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lession_proto_init() }
func file_lession_proto_init() {
	if File_lession_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lession_proto_rawDesc), len(file_lession_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lession_proto_goTypes,
		DependencyIndexes: file_lession_proto_depIdxs,
		MessageInfos:      file_lession_proto_msgTypes,
	}.Build()
	File_lession_proto = out.File
	file_lession_proto_goTypes = nil
	file_lession_proto_depIdxs = nil
}
