// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: lesson.porot

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating        float32                `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lession) Reset() {
	*x = Lession{}
	mi := &file_lesson_porot_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lession) ProtoMessage() {}

func (x *Lession) ProtoReflect() protoreflect.Message {
	mi := &file_lesson_porot_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lession.ProtoReflect.Descriptor instead.
func (*Lession) Descriptor() ([]byte, []int) {
	return file_lesson_porot_rawDescGZIP(), []int{0}
}

func (x *Lession) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lession) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

var File_lesson_porot protoreflect.FileDescriptor

const file_lesson_porot_rawDesc = "" +
	"\n" +
	"\flesson.porot\x12\bprotobuf\"E\n" +
	"\aLession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x02R\x06ratingB\fZ\n" +
	"./protobufb\x06proto3"

var (
	file_lesson_porot_rawDescOnce sync.Once
	file_lesson_porot_rawDescData []byte
)

func file_lesson_porot_rawDescGZIP() []byte {
	file_lesson_porot_rawDescOnce.Do(func() {
		file_lesson_porot_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lesson_porot_rawDesc), len(file_lesson_porot_rawDesc)))
	})
	return file_lesson_porot_rawDescData
}

var file_lesson_porot_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_lesson_porot_goTypes = []any{
	(*Lession)(nil), // 0: protobuf.Lession
}
var file_lesson_porot_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lesson_porot_init() }
func file_lesson_porot_init() {
	if File_lesson_porot != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lesson_porot_rawDesc), len(file_lesson_porot_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lesson_porot_goTypes,
		DependencyIndexes: file_lesson_porot_depIdxs,
		MessageInfos:      file_lesson_porot_msgTypes,
	}.Build()
	File_lesson_porot = out.File
	file_lesson_porot_goTypes = nil
	file_lesson_porot_depIdxs = nil
}
